{"uuid":"70a60da4-729b-4b7a-a309-0f1e611d3f7f","historyId":"db7273ec6ccbb5dc319e17172e77670c","fullName":"AwaitilityTests.waitUntilAndIgnoreSpecificException","labels":[{"name":"package","value":"AwaitilityTests"},{"name":"testClass","value":"AwaitilityTests"},{"name":"testMethod","value":"waitUntilAndIgnoreSpecificException"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"rest-assured-testng-framework"},{"name":"subSuite","value":"AwaitilityTests"},{"name":"host","value":"LAPTOP-HPHDFIQM"},{"name":"thread","value":"15668@LAPTOP-HPHDFIQM.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"waitUntilAndIgnoreSpecificException","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Condition with alias 'My custom message' didn't complete within 5 seconds because condition with Lambda expression in AwaitilityTests was not fulfilled.","trace":"org.awaitility.core.ConditionTimeoutException: Condition with alias 'My custom message' didn't complete within 5 seconds because condition with Lambda expression in AwaitilityTests was not fulfilled.\r\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)\r\n\tat org.awaitility.core.CallableCondition.await(CallableCondition.java:78)\r\n\tat org.awaitility.core.CallableCondition.await(CallableCondition.java:26)\r\n\tat org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)\r\n\tat org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)\r\n\tat AwaitilityTests.waitUntilAndIgnoreSpecificException(AwaitilityTests.java:63)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.lang.AssertionError: 1 expectation failed.\nExpected status code <400> but was <200>.\n\r\n\tat java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)\r\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)\r\n\tat org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)\r\n\tat org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)\r\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)\r\n\tat io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)\r\n\tat io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)\r\n\tat io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)\r\n\tat io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)\r\n\tat org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)\r\n\tat org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)\r\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)\r\n\tat io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)\r\n\tat io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)\r\n\tat io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)\r\n\tat io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)\r\n\tat AwaitilityTests.lambda$waitUntilAndIgnoreSpecificException$3(AwaitilityTests.java:64)\r\n\tat org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)\r\n\tat org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)\r\n\tat org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)\r\n\tat java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java)\r\n\tat --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)\r\n\tat java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)\r\n\tat java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)\r\n\tat java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:144)\r\n\tat java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:790)\r\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:101)\r\n\t... 30 more\r\n"},"stage":"finished","steps":[],"attachments":[{"name":"Request","source":"53bc1c40-20d9-4eb7-896c-991cb3dd7f75-attachment.html","type":"text/html"},{"name":"HTTP/1.1 200 OK","source":"b474cc02-bd85-404a-9eb7-bcbd713580f4-attachment.html","type":"text/html"}],"parameters":[],"start":1750272697573,"stop":1750272703704}